"""paper trading tables

Revision ID: 17eb4be42ed3
Revises: 23b927790140
Create Date: 2026-07-19 12:00:35.307978

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '17eb4be42ed3'
down_revision = '23b927790140'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('initial_cash', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('base_currency', sa.String(length=10), server_default='USD', nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('strategy_parameter_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parameter_hash', sa.String(length=64), nullable=False),
    sa.Column('settings_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_accounts_parameter_hash'), 'paper_accounts', ['parameter_hash'], unique=False)
    op.create_index(op.f('ix_paper_accounts_status'), 'paper_accounts', ['status'], unique=False)
    op.create_index(op.f('ix_paper_accounts_strategy_id'), 'paper_accounts', ['strategy_id'], unique=False)
    op.create_table('account_equity_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_account_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('cash', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('positions_value', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total_equity', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('daily_return', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('cumulative_return', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('drawdown', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_account_id', 'snapshot_date', name='uq_equity_snapshots_day')
    )
    op.create_index(op.f('ix_account_equity_snapshots_paper_account_id'), 'account_equity_snapshots', ['paper_account_id'], unique=False)
    op.create_table('paper_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_account_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('signal_date', sa.Date(), nullable=False),
    sa.Column('scheduled_execution_date', sa.Date(), nullable=True),
    sa.Column('executed_at', sa.Date(), nullable=True),
    sa.Column('execution_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('commission', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('slippage', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('status', sa.String(length=9), server_default='PENDING', nullable=False),
    sa.Column('rejection_reason', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_paper_orders_account_status', 'paper_orders', ['paper_account_id', 'status'], unique=False)
    op.create_index(op.f('ix_paper_orders_paper_account_id'), 'paper_orders', ['paper_account_id'], unique=False)
    op.create_index(op.f('ix_paper_orders_status'), 'paper_orders', ['status'], unique=False)
    op.create_index('uq_paper_orders_account_signal', 'paper_orders', ['paper_account_id', 'signal_id'], unique=True, postgresql_where=sa.text('signal_id IS NOT NULL'))
    op.create_table('paper_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_account_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('average_entry_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('opened_at', sa.Date(), nullable=False),
    sa.Column('closed_at', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=6), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_positions_paper_account_id'), 'paper_positions', ['paper_account_id'], unique=False)
    op.create_index(op.f('ix_paper_positions_status'), 'paper_positions', ['status'], unique=False)
    op.create_index(op.f('ix_paper_positions_stock_id'), 'paper_positions', ['stock_id'], unique=False)
    op.create_index('uq_paper_positions_open', 'paper_positions', ['paper_account_id', 'stock_id'], unique=True, postgresql_where=sa.text("status = 'OPEN'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_paper_positions_open', table_name='paper_positions', postgresql_where=sa.text("status = 'OPEN'"))
    op.drop_index(op.f('ix_paper_positions_stock_id'), table_name='paper_positions')
    op.drop_index(op.f('ix_paper_positions_status'), table_name='paper_positions')
    op.drop_index(op.f('ix_paper_positions_paper_account_id'), table_name='paper_positions')
    op.drop_table('paper_positions')
    op.drop_index('uq_paper_orders_account_signal', table_name='paper_orders', postgresql_where=sa.text('signal_id IS NOT NULL'))
    op.drop_index(op.f('ix_paper_orders_status'), table_name='paper_orders')
    op.drop_index(op.f('ix_paper_orders_paper_account_id'), table_name='paper_orders')
    op.drop_index('ix_paper_orders_account_status', table_name='paper_orders')
    op.drop_table('paper_orders')
    op.drop_index(op.f('ix_account_equity_snapshots_paper_account_id'), table_name='account_equity_snapshots')
    op.drop_table('account_equity_snapshots')
    op.drop_index(op.f('ix_paper_accounts_strategy_id'), table_name='paper_accounts')
    op.drop_index(op.f('ix_paper_accounts_status'), table_name='paper_accounts')
    op.drop_index(op.f('ix_paper_accounts_parameter_hash'), table_name='paper_accounts')
    op.drop_table('paper_accounts')
    # ### end Alembic commands ###
