"""backtest tables

Revision ID: 23b927790140
Revises: 80ca513135a8
Create Date: 2026-07-19 00:21:17.760181

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '23b927790140'
down_revision = '80ca513135a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parameters_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parameter_hash', sa.String(length=64), nullable=False),
    sa.Column('universe_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('settings_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('commission_model_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('slippage_model_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('initial_cash', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='PENDING', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('results_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_runs_status'), 'backtest_runs', ['status'], unique=False)
    op.create_index('ix_backtest_runs_strategy_created', 'backtest_runs', ['strategy_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_backtest_runs_strategy_id'), 'backtest_runs', ['strategy_id'], unique=False)
    op.create_table('backtest_skipped_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backtest_run_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('signal_date', sa.Date(), nullable=False),
    sa.Column('signal_type', sa.String(length=4), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('detail', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_skipped_signals_backtest_run_id'), 'backtest_skipped_signals', ['backtest_run_id'], unique=False)
    op.create_table('backtest_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backtest_run_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('entry_signal_date', sa.Date(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('exit_signal_date', sa.Date(), nullable=True),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('commission_paid', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('pnl_percent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('holding_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=6), nullable=False),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_trades_backtest_run_id'), 'backtest_trades', ['backtest_run_id'], unique=False)
    op.create_index('ix_backtest_trades_run_entry', 'backtest_trades', ['backtest_run_id', 'entry_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_backtest_trades_run_entry', table_name='backtest_trades')
    op.drop_index(op.f('ix_backtest_trades_backtest_run_id'), table_name='backtest_trades')
    op.drop_table('backtest_trades')
    op.drop_index(op.f('ix_backtest_skipped_signals_backtest_run_id'), table_name='backtest_skipped_signals')
    op.drop_table('backtest_skipped_signals')
    op.drop_index(op.f('ix_backtest_runs_strategy_id'), table_name='backtest_runs')
    op.drop_index('ix_backtest_runs_strategy_created', table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_status'), table_name='backtest_runs')
    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
