"""competitions

Revision ID: 3d9debd91097
Revises: e0375171158c
Create Date: 2026-07-19 12:25:59.271752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d9debd91097'
down_revision = 'e0375171158c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competition_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('paper_account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id', 'paper_account_id', name='uq_competition_account')
    )
    op.create_index(op.f('ix_competition_accounts_competition_id'), 'competition_accounts', ['competition_id'], unique=False)
    op.create_index(op.f('ix_competition_accounts_paper_account_id'), 'competition_accounts', ['paper_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competition_accounts_paper_account_id'), table_name='competition_accounts')
    op.drop_index(op.f('ix_competition_accounts_competition_id'), table_name='competition_accounts')
    op.drop_table('competition_accounts')
    op.drop_table('competitions')
    # ### end Alembic commands ###
