"""indicators, strategies, signals

Revision ID: 450eff0312af
Revises: 31f6df9a10f8
Create Date: 2026-07-18 18:06:05.109696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '450eff0312af'
down_revision = '31f6df9a10f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('strategy_type', sa.String(length=60), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('parameters_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_strategies_name_version')
    )
    op.create_index(op.f('ix_strategies_is_active'), 'strategies', ['is_active'], unique=False)
    op.create_index(op.f('ix_strategies_strategy_type'), 'strategies', ['strategy_type'], unique=False)
    op.create_table('daily_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('sma_20', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('sma_50', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('sma_150', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('average_volume', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('volume_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sma_150_slope', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'trade_date', name='uq_daily_indicators_stock_date')
    )
    op.create_index(op.f('ix_daily_indicators_stock_id'), 'daily_indicators', ['stock_id'], unique=False)
    op.create_index('ix_daily_indicators_stock_trade_date', 'daily_indicators', ['stock_id', 'trade_date'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('signal_type', sa.String(length=4), nullable=False),
    sa.Column('execution_date', sa.Date(), nullable=True),
    sa.Column('reference_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('conditions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parameter_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parameter_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'strategy_id', 'trade_date', 'signal_type', 'parameter_hash', name='uq_signals_dedupe')
    )
    op.create_index(op.f('ix_signals_stock_id'), 'signals', ['stock_id'], unique=False)
    op.create_index('ix_signals_stock_trade_date', 'signals', ['stock_id', 'trade_date'], unique=False)
    op.create_index(op.f('ix_signals_strategy_id'), 'signals', ['strategy_id'], unique=False)
    op.create_index('ix_signals_strategy_trade_date', 'signals', ['strategy_id', 'trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_signals_strategy_trade_date', table_name='signals')
    op.drop_index(op.f('ix_signals_strategy_id'), table_name='signals')
    op.drop_index('ix_signals_stock_trade_date', table_name='signals')
    op.drop_index(op.f('ix_signals_stock_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index('ix_daily_indicators_stock_trade_date', table_name='daily_indicators')
    op.drop_index(op.f('ix_daily_indicators_stock_id'), table_name='daily_indicators')
    op.drop_table('daily_indicators')
    op.drop_index(op.f('ix_strategies_strategy_type'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_is_active'), table_name='strategies')
    op.drop_table('strategies')
    # ### end Alembic commands ###
