"""telegram_alerts

Revision ID: 80ca513135a8
Revises: 450eff0312af
Create Date: 2026-07-18 23:39:10.130865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ca513135a8'
down_revision = '450eff0312af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='PENDING', nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('telegram_message_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id', name='uq_telegram_alerts_signal')
    )
    op.create_index(op.f('ix_telegram_alerts_signal_id'), 'telegram_alerts', ['signal_id'], unique=False)
    op.create_index(op.f('ix_telegram_alerts_status'), 'telegram_alerts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_alerts_status'), table_name='telegram_alerts')
    op.drop_index(op.f('ix_telegram_alerts_signal_id'), table_name='telegram_alerts')
    op.drop_table('telegram_alerts')
    # ### end Alembic commands ###
