"""trade date index

Revision ID: e0375171158c
Revises: 17eb4be42ed3
Create Date: 2026-07-19 12:10:07.681523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0375171158c'
down_revision = '17eb4be42ed3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_daily_prices_trade_date', 'daily_prices', ['trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_daily_prices_trade_date', table_name='daily_prices')
    # ### end Alembic commands ###
