import { useQuery } from '@tanstack/react-query'
import { Fragment, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { getSignals } from '../api/signals.js'
import { listAllStocks } from '../api/stocks.js'
import { listStrategies } from '../api/strategies.js'
import StatusBadge from '../components/StatusBadge.jsx'
import { formatCompact, formatPrice } from '../utils/format.js'

const TYPES = [
  ['', 'All'],
  ['buy', 'Buy'],
  ['sell', 'Sell'],
]

export default function Signals() {
  const [signalType, setSignalType] = useState('')
  const [strategyId, setStrategyId] = useState('')
  const [since, setSince] = useState('')
  const [expanded, setExpanded] = useState(null)

  const strategiesQ = useQuery({ queryKey: ['strategies'], queryFn: listStrategies })
  const stocksQ = useQuery({
    queryKey: ['all-stocks'],
    queryFn: listAllStocks,
    staleTime: 5 * 60_000,
  })

  const params = useMemo(() => {
    const p = { limit: 200 }
    if (signalType) p.signal_type = signalType
    if (strategyId) p.strategy_id = Number(strategyId)
    if (since) p.since = since
    return p
  }, [signalType, strategyId, since])

  const { data, isPending, isError, error } = useQuery({
    queryKey: ['signals', params],
    queryFn: () => getSignals(params),
    placeholderData: (prev) => prev,
  })

  // Signals carry stock_id, not a symbol — join against the stock list.
  const stockById = useMemo(() => {
    const map = {}
    for (const s of stocksQ.data ?? []) map[s.id] = s
    return map
  }, [stocksQ.data])

  const strategyName = (id) =>
    strategiesQ.data?.find((s) => s.id === id)?.name ?? `Strategy #${id}`

  const rows = data?.items ?? []

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-baseline justify-between gap-2">
        <h1 className="text-2xl font-semibold">Signals</h1>
        <p className="text-xs text-slate-500">
          {data ? `${data.count} signal${data.count === 1 ? '' : 's'}` : ''} · transition events
          (state turned on that day) across all tracked stocks
        </p>
      </div>

      {/* Filters */}
      <div className="flex flex-wrap items-center gap-2 rounded-lg border border-slate-800 bg-slate-900 p-3 text-sm">
        <div className="inline-flex overflow-hidden rounded border border-slate-700">
          {TYPES.map(([value, label]) => (
            <button
              key={value || 'all'}
              onClick={() => setSignalType(value)}
              className={`px-3 py-1.5 text-xs ${
                signalType === value
                  ? 'bg-slate-800 text-emerald-400'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              {label}
            </button>
          ))}
        </div>
        <select
          value={strategyId}
          onChange={(e) => setStrategyId(e.target.value)}
          className="rounded border border-slate-700 bg-slate-950 px-2 py-1.5"
        >
          <option value="">All strategies</option>
          {(strategiesQ.data ?? []).map((s) => (
            <option key={s.id} value={s.id}>
              {s.name}
            </option>
          ))}
        </select>
        <label className="flex items-center gap-1.5 text-xs text-slate-400">
          Since
          <input
            type="date"
            value={since}
            onChange={(e) => setSince(e.target.value)}
            className="rounded border border-slate-700 bg-slate-950 px-2 py-1.5 text-slate-100"
          />
        </label>
        {since && (
          <button
            onClick={() => setSince('')}
            className="rounded border border-slate-700 px-2 py-1.5 text-xs text-slate-400 hover:text-slate-200"
          >
            Clear date
          </button>
        )}
      </div>

      <div className="overflow-x-auto rounded-lg border border-slate-800 bg-slate-900">
        {isPending && <p className="p-6 text-sm text-slate-400">Loading signals…</p>}
        {isError && <p className="p-6 text-sm text-red-400">Failed to load: {error?.message}</p>}
        {data && rows.length === 0 && (
          <p className="p-6 text-sm text-slate-400">
            No signals match these filters. Signals are generated by the nightly scan; try a wider
            date range or a different type.
          </p>
        )}
        {data && rows.length > 0 && (
          <table className="w-full text-sm tabular-nums">
            <thead className="border-b border-slate-800 text-left text-[11px] text-slate-400 uppercase">
              <tr>
                <th className="px-3 py-2">Date</th>
                <th className="px-3 py-2">Symbol</th>
                <th className="px-3 py-2">Company</th>
                <th className="px-3 py-2">Type</th>
                <th className="px-3 py-2 text-right">Reference price</th>
                <th className="px-3 py-2">Execution</th>
                <th className="px-3 py-2">Strategy</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/60">
              {rows.map((signal) => {
                const stock = stockById[signal.stock_id]
                const isSell = signal.signal_type === 'SELL'
                const values = signal.conditions_json?.values ?? {}
                const open = expanded === signal.id
                return (
                  <Fragment key={signal.id}>
                    <tr
                      onClick={() => setExpanded(open ? null : signal.id)}
                      className="cursor-pointer hover:bg-slate-800/50"
                    >
                      <td className="px-3 py-2 text-slate-300">{signal.trade_date}</td>
                      <td className="px-3 py-2 font-medium text-slate-100">
                        {stock ? (
                          <Link
                            to={`/stocks/${stock.symbol}`}
                            onClick={(e) => e.stopPropagation()}
                            className="hover:text-emerald-400"
                          >
                            {stock.symbol}
                          </Link>
                        ) : (
                          <span className="text-slate-500">#{signal.stock_id}</span>
                        )}
                      </td>
                      <td className="max-w-56 truncate px-3 py-2 text-slate-400">
                        {stock?.company_name ?? '—'}
                      </td>
                      <td className="px-3 py-2">
                        <StatusBadge kind={isSell ? 'down' : 'ok'}>{signal.signal_type}</StatusBadge>
                      </td>
                      <td className="px-3 py-2 text-right text-slate-300">
                        {formatPrice(signal.reference_price)}
                      </td>
                      <td className="px-3 py-2 text-xs text-slate-500">
                        {signal.execution_date ?? 'next open (pending)'}
                      </td>
                      <td className="px-3 py-2 text-xs text-slate-400">
                        {strategyName(signal.strategy_id)}
                      </td>
                    </tr>
                    {open && (
                      <tr className="bg-slate-950/60">
                        <td colSpan={7} className="px-3 py-3">
                          <div className="flex flex-wrap gap-2">
                            {Object.entries(values).length === 0 && (
                              <span className="text-xs text-slate-500">
                                No condition values recorded for this signal.
                              </span>
                            )}
                            {Object.entries(values).map(([key, val]) => (
                              <span
                                key={key}
                                className="rounded border border-slate-700 bg-slate-900 px-2 py-1 text-xs text-slate-300"
                              >
                                <span className="text-slate-500">{key}:</span>{' '}
                                {val == null ? '—' : formatCompact(val)}
                              </span>
                            ))}
                          </div>
                        </td>
                      </tr>
                    )}
                  </Fragment>
                )
              })}
            </tbody>
          </table>
        )}
      </div>
    </div>
  )
}
